pipeline {
    agent any



    stages {
        stage('Git') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/mohamedbizani/DEVOPS-Project.git'
            }
        }

       stage('Build') {
           steps {
               dir('kaddem') {  // Exécute la commande Maven dans le bon dossier
                   sh 'mvn clean compile'
               }
           }
       }
       stage('SonarQube Analysis') {
                   steps {
                       dir('kaddem') {
                           sh 'mvn sonar:sonar -Dsonar.projectKey=DEVOPS-Project -Dsonar.host.url=http://192.168.33.10:9000 -Dsonar.login=sonarqube'
                       }
                   }
               }



        }
        }
