pipeline {
    agent any



    stages {
        stage('Git') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/mohamedbizani/DEVOPS-Project.git'
            }
        }

       stage('Build') {
           steps {
               dir('kaddem') {  // Exécute la commande Maven dans le bon dossier
                   sh 'mvn clean compile'
               }
           }
       }

        }
        }
